#!/usr/bin/env bash

set -e

echo "Setting up dev environment..."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Do the following on MacOS only
if [[ $(uname) == "Darwin" ]]; then
  echo "MacOS Detected"
  # Install brew
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
  else
    echo "Homebrew already installed, updating..."
    brew update
  fi
  # Install apps & packages with Brewfile
  echo "Installing packages and apps with Homebrew & Cask..."
  brew bundle --file=dependencies/Brewfile --no-lock --no-upgrade
fi

#### Shell (zsh) configuration ####
# Install Oh My Zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then
  # Install Oh My Zsh
  echo "Installing Oh My Zsh..."
  RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
else
  # Use the inbuilt mechanism to update Oh My Zsh
  echo "Oh My Zsh already installed, updating..."
  cd $HOME/.oh-my-zsh
  git pull
  cd $HOME/dotfiles
fi

# Install Powerlevel10k zsh theme
if [[ ! -d $HOME/.oh-my-zsh/custom/themes/powerlevel10k ]]; then
  echo "Installing Powerlevel10k zsh theme..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
else
  echo "Powerlevel10k already installed, updating..."
  cd $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  git pull
  cd $HOME/dotfiles
fi

# Install additional zsh plugins not included with Oh My Zsh
for r in zsh-autosuggestions zsh-syntax-highlighting; do
  if [[ ! -d $HOME/.oh-my-zsh/custom/plugins/$r ]]; then
    echo "Installing $r..."
    git clone --depth=1 https://github.com/zsh-users/$r $HOME/.oh-my-zsh/custom/plugins/$r
  else
    echo "$r already installed, updating..."
    cd $HOME/.oh-my-zsh/custom/plugins/$r
    git pull
    cd $HOME/dotfiles
  fi
done

# Link custom .zsh files to Oh My Zsh custom folder
if [[ ! -f custom/secret.zsh ]]; then
  touch custom/secret.zsh
fi
for f in custom/*; do
  echo "Linking custom .zsh files..."
  ln -sf $HOME/dotfiles/$f $HOME/.oh-my-zsh/$f
done

# Link ssh config
echo "Linking ssh config..."
mkdir -p $HOME/.ssh
ln -sf $HOME/dotfiles/ssh/config $HOME/.ssh/config

# Link $HOME dotfiles
echo "Linking files to home directory..."
for f in *; do
  if [[ $f == "README.md" || $f == "install" ]]; then
    echo "Ignoring special file $f"
  elif [[ -d $f ]]; then
    echo "Ignoring directory $f"
  else
    ln -sf $HOME/dotfiles/$f $HOME/.$f
  fi
done

# Create this file to suppress error from z on first 'cd'
touch $HOME/.z

# Change the users default shell
echo "Changing the default shell..."
sudo chsh -s /usr/local/bin/zsh $USER

# Install asdf version manager plugins
for p in nodejs ruby yarn; do
  if [[ ! -d $HOME/.asdf/plugins/$p ]]; then
    echo "Installing asdf plugin $p..."
    asdf plugin add $p
    if [[ $p == "nodejs" ]]; then
      bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
    fi
  else
    echo "asdf plugin $p already installed, updating..."
    asdf plugin update $p
  fi
done

# Install default versions
asdf install

echo "Setup complete, quit terminal and open iTerm to continue..."
