#!/usr/bin/env bash

set -e

echo "Setting up dev environment..."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

WORKDIR=$(pwd)

# Do the following on MacOS only
if [[ $(uname) == "Darwin" ]]; then
  echo "MacOS Detected"
  # Install brew
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
  else
    echo "Homebrew already installed, updating..."
    brew update
  fi
  # Install apps & packages with Brewfile
  echo "Installing packages and apps with Homebrew..."
  brew bundle --file=dependencies/Brewfile --no-lock --no-upgrade
fi

#### Shell (zsh) configuration ####
# Install Oh My Zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then
  # Install Oh My Zsh
  echo "Installing Oh My Zsh..."
  RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
else
  # Use the inbuilt mechanism to update Oh My Zsh
  echo "Oh My Zsh already installed, updating..."
  cd $HOME/.oh-my-zsh
  git pull >/dev/null 2>&1
  cd $HOME/dotfiles
fi

# Install Powerlevel10k zsh theme
if [[ ! -d $HOME/.oh-my-zsh/custom/themes/powerlevel10k ]]; then
  echo "Installing Powerlevel10k zsh theme..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
else
  echo "Powerlevel10k already installed, updating..."
  cd $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  git pull >/dev/null 2>&1
  cd $HOME/dotfiles
fi

# Install additional zsh plugins not included with Oh My Zsh
for plugin_name in zsh-autosuggestions zsh-syntax-highlighting; do
  if [[ ! -d $HOME/.oh-my-zsh/custom/plugins/$plugin_name ]]; then
    echo "Installing $plugin_name..."
    git clone --depth=1 https://github.com/zsh-users/$plugin_name $HOME/.oh-my-zsh/custom/plugins/$plugin_name
  else
    echo "$plugin_name already installed, updating..."
    cd $HOME/.oh-my-zsh/custom/plugins/$plugin_name
    git pull >/dev/null 2>&1
    cd $HOME/dotfiles
  fi
done

# Link custom .zsh files to Oh My Zsh custom folder
if [[ ! -f custom/secret.zsh ]]; then
  touch custom/secret.zsh
fi
for file in custom/*; do
  echo "Linking custom .zsh files..."
  ln -sf $HOME/dotfiles/$file $HOME/.oh-my-zsh/$file
done

# Link ssh config
echo "Linking ssh config..."
mkdir -p $HOME/.ssh
ln -sf $HOME/dotfiles/ssh/config $HOME/.ssh/config

# Link $HOME dotfiles
echo "Linking files to home directory..."
for file in *; do
  if [[ $file == "README.md" || $file == "install" ]]; then
    echo "Ignoring special file $file"
  elif [[ -d $file ]]; then
    echo "Ignoring directory $file"
  else
    ln -sf $HOME/dotfiles/$file $HOME/.$file
  fi
done

# Create this file to suppress error from z on first 'cd'
if [[ ! -f $HOME/.z ]]; then
    touch $HOME/.z
fi

# Install asdf version manager plugins
for p in ruby nodejs yarn kubectl; do
  if [[ ! -d $HOME/.asdf/plugins/$p ]]; then
    echo "Installing asdf plugin $p..."
    asdf plugin add $p
    if [[ $p == "nodejs" ]]; then
      bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
    fi
  else
    echo "asdf plugin $p already installed, updating..."
    asdf plugin update $p
  fi
done

# Install default versions
asdf install

# Restore configs with mackup
echo "Linking mackup config..."
if [[ ! -d $HOME/.mackup ]]; then
    mkdir -p $HOME/.mackup
fi
for f in mackup/*; do
    ln -sf $WORKDIR/$f $HOME/.$f
done
echo "Restoring files with mackup..."
mackup restore -f

# Change the users default shell
if [[ $SHELL != "$(brew --prefix)/bin/zsh" ]]; then
    echo "Changing the default shell..."
    sudo chsh -s $(brew --prefix)/bin/zsh $USER
fi

echo "Setup complete, quit terminal and open iTerm to continue..."
