tap "homebrew/cask-fonts"
tap "homebrew/services"


tap "epk/epk" # SF Mono Nerd Font
tap "koekeishiya/formulae" # skhd & yabai


## CLI
# GitHub's own specific CLI
brew "gh"
# Distributed revision control system
brew "git"
# Keep your Mac's application settings in sync
brew "mackup"
# NeoVim, get on it
brew "neovim"
# Simple keyboard hotkey daemon, counterpart of yabai
brew "skhd"
# Automagic window management
brew "yabai"
# Tracks most-used directories to make cd smarter
brew "z"


## Casks (GUI)
cask "font-sf-mono-nerd-font"
cask "karabiner-elements"
cask "linearmouse"
