# tap "koekeishiya/formulae" # skhd
tap "nikitabobko/tap"


## CLI
# GitHub's own specific CLI
brew "gh"
# Distributed revision control system
brew "git"
# A better git diff, used in `~/.config/git/config`
brew "difftastic"
# Keep your Mac's application settings in sync
brew "stow"
# NeoVim, get on it
brew "neovim"
# Terminal multiplexer
brew "tmux"


## Casks (GUI)
cask "aerospace"
cask "alacritty"
cask "appcleaner"
# cask "ghostty"
# cask "kap"
cask "karabiner-elements"
# cask "monitorcontrol"
# cask "rectangle-pro"
# cask "roon"
cask "zed"

## Fonts
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
