#!/usr/bin/env sh

# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config window_origin_display      default
yabai -m config window_placement           second_child
yabai -m config window_topmost             off
yabai -m config window_shadow              on
yabai -m config window_opacity             off
yabai -m config window_opacity_duration    0.0
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      0.90
yabai -m config window_border              on
yabai -m config window_border_width        6
yabai -m config active_window_border_color 0xff00ff00
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color      0xffd75f5f
yabai -m config split_ratio                0.50
yabai -m config auto_balance               off

# general space settings
yabai -m config layout                     bsp
yabai -m config top_padding                20
yabai -m config bottom_padding             20
yabai -m config left_padding               20
yabai -m config right_padding              20
yabai -m config window_gap                 10

# mouse settings
yabai -m config mouse_follows_focus        on
yabai -m config focus_follows_mouse        off
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap

# apps to not manage
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Battle.net$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app="^PS Remote Play$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^World of Warcraft$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded..."
